# require 'rails_delete_all_and_assocs_without_instantiation'
require 'rails'
require_relative 'rails_delete_all_and_assocs_without_instantiation/delete_all_and_assocs_extension'

ActiveRecord::Base.extend(
  RailsDeleteAllAndAssocsWithoutInstantiation::DeleteAllAndAssocsWithoutInstantiation
)